"""add contract status history

Revision ID: 2a3a882cf008
Revises: da5b270cb6f8
Create Date: 2026-07-21 09:28:00.585178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3a882cf008'
down_revision: Union[str, Sequence[str], None] = 'da5b270cb6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_status_history_changed_at'), 'contract_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_contract_status_history_contract_id'), 'contract_status_history', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_status_history_contract_id'), table_name='contract_status_history')
    op.drop_index(op.f('ix_contract_status_history_changed_at'), table_name='contract_status_history')
    op.drop_table('contract_status_history')
    # ### end Alembic commands ###
