"""add director position to organization profile

Revision ID: 5066d7fde410
Revises: dac24868217d
Create Date: 2026-07-22 10:31:10.801778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5066d7fde410'
down_revision: Union[str, Sequence[str], None] = 'dac24868217d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_profiles', sa.Column('director_position', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_profiles', 'director_position')
    # ### end Alembic commands ###
