"""create counterparties table

Revision ID: 773d172f982d
Revises: e09914b94060
Create Date: 2026-07-16 11:03:22.927675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773d172f982d'
down_revision: Union[str, Sequence[str], None] = 'e09914b94060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unp', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_unp'), 'counterparties', ['unp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_unp'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
