"""add contract party roles

Revision ID: cb3db4533373
Revises: 70b2ee05b070
Create Date: 2026-07-17 11:03:01.314949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3db4533373'
down_revision: Union[str, Sequence[str], None] = '70b2ee05b070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('owner_role', sa.String(length=50), server_default='supplier', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'owner_role')
    # ### end Alembic commands ###
