"""add document templates and technical specifications

Revision ID: dac24868217d
Revises: ef703d1ed53d
Create Date: 2026-07-21 10:54:53.502573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dac24868217d'
down_revision: Union[str, Sequence[str], None] = 'ef703d1ed53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('required_variables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_archived_at'), 'document_templates', ['archived_at'], unique=False)
    op.create_index(op.f('ix_document_templates_is_active'), 'document_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_templates_template_type'), 'document_templates', ['template_type'], unique=False)
    op.create_table('technical_specifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('procurement_subject', sa.String(length=1000), nullable=False),
    sa.Column('procurement_procedure', sa.String(length=255), server_default='Открытый конкурс', nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=False),
    sa.Column('internal_regulation_document', sa.Text(), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('work_start_date', sa.Date(), nullable=True),
    sa.Column('work_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('generated_file_name', sa.String(length=255), nullable=True),
    sa.Column('generated_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_specifications_archived_at'), 'technical_specifications', ['archived_at'], unique=False)
    op.create_index(op.f('ix_technical_specifications_contract_id'), 'technical_specifications', ['contract_id'], unique=False)
    op.create_index(op.f('ix_technical_specifications_counterparty_id'), 'technical_specifications', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_technical_specifications_status'), 'technical_specifications', ['status'], unique=False)
    op.create_index(op.f('ix_technical_specifications_template_id'), 'technical_specifications', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_specifications_template_id'), table_name='technical_specifications')
    op.drop_index(op.f('ix_technical_specifications_status'), table_name='technical_specifications')
    op.drop_index(op.f('ix_technical_specifications_counterparty_id'), table_name='technical_specifications')
    op.drop_index(op.f('ix_technical_specifications_contract_id'), table_name='technical_specifications')
    op.drop_index(op.f('ix_technical_specifications_archived_at'), table_name='technical_specifications')
    op.drop_table('technical_specifications')
    op.drop_index(op.f('ix_document_templates_template_type'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_is_active'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_archived_at'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
