"""add contract events

Revision ID: ef703d1ed53d
Revises: 2a3a882cf008
Create Date: 2026-07-21 09:58:36.917130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef703d1ed53d'
down_revision: Union[str, Sequence[str], None] = '2a3a882cf008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_events_contract_id'), 'contract_events', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_events_created_at'), 'contract_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_contract_events_event_type'), 'contract_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_events_event_type'), table_name='contract_events')
    op.drop_index(op.f('ix_contract_events_created_at'), table_name='contract_events')
    op.drop_index(op.f('ix_contract_events_contract_id'), table_name='contract_events')
    op.drop_table('contract_events')
    # ### end Alembic commands ###
